# netlify.toml
[build]
  base    = "frontend"               # entra en la carpeta frontend
  publish = "dist"                   # publica dist/, no frontend/dist
  command = "npm install && npm run build"

[[redirects]]
  from   = "/*"                      # para tu SPA React
  to     = "/index.html"
  status = 200
